[NEW] Rest users active
RocketChat/Rocket.Chat.Docs pull request #1026
Opened 2018-12-14 21:22 UTC by MarcosSpessatto

Closes https://github.com/RocketChat/docs/issues/1023
Waiting https://github.com/RocketChat/Rocket.Chat/pull/12800

2018-12-14 21:26 UTC, sampaiodiego approved these changes

2019-05-20 06:50 UTC, geekgonecrazy requested changes

2019-05-20 06:50 UTC, geekgonecrazy commented on _data/toc.yml
> +        - active
```suggestion
        - presence
```

2019-05-20 06:50 UTC, geekgonecrazy commented on contributing/documentation/documentation-map/README.md
> +            - active
```suggestion
            - presence
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/README.md
> +| `/api/v1/users.active`                        | Gets all active users.                                          | [Link](users/active/)                        |
```suggestion
| `/api/v1/users.presence`                        | Gets all connected users presence.                                          | [Link](users/presence/)                        |
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/users/README.md
> +| `/api/v1/users.active` | Gets all active users. | [Link](active/) |
```suggestion
| `/api/v1/users.presence` | Gets all connected users presence. | [Link](presence/) |
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/users/active/README.md
> +# User Active
```suggestion
# Users Presence
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/users/active/README.md
> +Gets all active users.
```suggestion
Gets all connected users presence.
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/users/active/README.md
> +| `/api/v1/users.active` | `yes` | `GET` |
```suggestion
| `/api/v1/users.presence` | `yes` | `GET` |
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/users/active/README.md
> +     http://localhost:3000/api/v1/users.active
```suggestion
     http://localhost:3000/api/v1/users.presence
```

2019-05-20 06:50 UTC, geekgonecrazy commented on developer-guides/rest-api/users/active/README.md
> +| 0.73.0 | Added |
```suggestion
| 1.1.0 | Added |
```

2019-05-20 06:55 UTC, geekgonecrazy commented
Changed with new endpoint: https://github.com/RocketChat/Rocket.Chat/pull/14488

2019-05-20 12:11 UTC, MarcosSpessatto commented
Wow, thanks for updating the docs @geekgonecrazy :1st_place_medal:

2019-05-22 12:32 UTC, sampaiodiego commented
guys I added the `from` parameter description and some docs about the stream payload.

Please review as I'm not sure the wording. thanks

2019-05-22 19:13 UTC, geekgonecrazy approved these changes

2019-05-22 19:14 UTC, geekgonecrazy commented
LGTM 👍

2019-05-23 12:43 UTC, merged