Update documentation of File Upload section
RocketChat/Rocket.Chat.Docs pull request #1152
Opened 2019-03-21 18:40 UTC by Pratyush1197

In the File upload section of File system documentation is missing for the instructions to specify the path where the uploaded file be stored.

2019-09-16 14:40 UTC, MartinSchoeler requested changes

2019-09-16 14:40 UTC, MartinSchoeler commented on contributing/google-summer-of-code-2019/README.md
> +### Integrating Auto translation with Augmented Reality
Please remove the unrelated changes from this PR

2019-09-16 14:40 UTC, MartinSchoeler commented on administrator-guides/file-upload/Local-file-system/README.md
> +# Local File Storage
Can you add this file to the table of contents?

2020-11-25 17:20 UTC, Faria-TechWrite approved these changes

2020-11-25 17:36 UTC, closed without merging