Update README.md
RocketChat/Rocket.Chat.Docs pull request #1154
Opened 2019-03-22 17:29 UTC by ubarsaiyan

2019-04-08 00:08 UTC, kerolloz requested changes
please have more meaningful commit messages

2019-04-08 17:17 UTC, ubarsaiyan commented
@kerolloz sorry! Should I resend the PR?

2020-05-28 21:13 UTC, grahamsmith approved these changes

2020-06-08 21:32 UTC, grahamsmith commented
Thanks for your contribution! We have added the contents in another PR and are going to close this one. Thanks again!

2020-06-08 21:32 UTC, closed without merging