Make permission and permissions be consistent (#1206)
RocketChat/Rocket.Chat.Docs pull request #1207
Opened 2019-04-04 17:18 UTC by lolimay

Closes #1206

2019-04-08 00:12 UTC, kerolloz requested changes

2019-04-08 00:12 UTC, kerolloz commented on administrator-guides/permissions/README.md
>  Rocket.Chat has a vast and customizable permissions system. Most of the actions a user can make requires a certain permission so you can customize what users can do and see.
```suggestion
Rocket.Chat has a vast and customizable permissions system. Most of the actions a user can make require certain permission so you can customize what users can do and see.
```

2019-04-08 00:12 UTC, kerolloz commented on administrator-guides/permissions/README.md
>  Rocket.Chat has a vast and customizable permissions system. Most of the actions a user can make requires a certain permission so you can customize what users can do and see.
fixing some grammar mistakes.

2019-04-16 00:52 UTC, lolimay commented on administrator-guides/permissions/README.md
>  Rocket.Chat has a vast and customizable permissions system. Most of the actions a user can make requires a certain permission so you can customize what users can do and see.
Thanks

2019-04-24 14:17 UTC, merged