Add info about console.log
RocketChat/Rocket.Chat.Docs pull request #130
Opened 2016-11-25 08:44 UTC by milep

May need a better phrasing.

2016-11-25 08:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=130) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=130) before we can accept your contribution.<br/>

2016-11-28 04:16 UTC, geekgonecrazy requested changes

2016-11-28 04:16 UTC, geekgonecrazy commented on 5. Administrator Guides/Integrations/README.md
> +You can use the **console** to log and view the logs from Administration -> View Logs.
Maybe we should include a link to: https://developer.mozilla.org/en-US/docs/Web/API/Console/log

2016-11-28 04:17 UTC, geekgonecrazy commented
Thanks for contributing!  Left a note.  Might be useful to give some context as to what console is for those that don't understand :)

2016-11-28 19:55 UTC, engelgabriel commented on 5. Administrator Guides/Integrations/README.md
> +You can use the **console** to log and view the logs from Administration -> View Logs.
@geekgonecrazy can you add your suggestion directly?

2016-11-28 22:58 UTC, geekgonecrazy commented on 5. Administrator Guides/Integrations/README.md
> +You can use the **console** to log and view the logs from Administration -> View Logs.
@engelgabriel Ah looks like that is enabled now!  Sweet.  Changes made.

2016-11-28 22:58 UTC, geekgonecrazy submitted a review, later dismissed

2016-11-29 21:01 UTC, engelgabriel approved these changes

2016-11-29 21:02 UTC, merged