Add notifications preference section
RocketChat/Rocket.Chat.Docs pull request #1328
Opened 2019-06-03 23:35 UTC by pradumangoyal

This will resolve a review in #1325 adding a Notifications Preference section so that it can be linked in the description of `Custom Sounds`.

2019-06-03 23:46 UTC, pradumangoyal commented
![image](https://user-images.githubusercontent.com/34851451/58841508-ced0ad00-8687-11e9-802b-ff63242e392b.png)
The build is failing at a place where I tried to link Custom Sound with it. The build will pass once #1325 is merged after this.

2019-06-04 13:01 UTC, MartinSchoeler requested changes

2019-06-04 13:01 UTC, MartinSchoeler commented on user-guides/channels/README.md
> +> There are some default choices for audio provided by Rocket chat. However, you also get to choose custom audio files for the same. Get further information about [Custom Sounds](../../administrator-
I think here we should specify that only an admin (or someone with the permission) can add custom sound files, so normal users don't think that everyone can do that, only to find out it's an administration tool.

2019-06-07 19:11 UTC, MartinSchoeler approved these changes
Looks good to me

2019-06-07 19:11 UTC, merged