More gsod projects
RocketChat/Rocket.Chat.Docs pull request #1343
Opened 2019-06-16 15:40 UTC by shubhangibharti

2019-06-16 15:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/docs?pullRequest=1343) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/docs?pullRequest=1343) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/docs?pullRequest=1343) it.</sub>

2019-06-16 19:35 UTC, shubhangibharti commented
Hi maintainers,

I am a GSoD applicant, have read your ideas list and working on closing tickets present in the list.

I have participated in multiple SoC/WoC and have been involved w/ open source. I have worked with Rest APIs and the project of Application Programming Interfaces (APIs) Documentation seems like a right fit for me.

On docs I like detailed docs having a list of hyperlinked headings, so I've added the feature.

2019-07-19 17:52 UTC, MartinSchoeler requested changes
An easier way to do this is reducing the header level on the titles (reducing from `###` to `##`) this will make the titles show up on the right table of contents.

Also, it seems that this PR wants to merge on a branch that is not master, please check your PR again.

Thanks!

2019-09-09 16:42 UTC, MartinSchoeler commented
Closing this due lack of response.

2019-09-09 16:42 UTC, closed without merging