Rocket.Chat Services deprecation notice
RocketChat/Rocket.Chat.Docs pull request #1427
Opened 2019-10-02 05:42 UTC by geekgonecrazy

2019-10-02 11:46 UTC, sampaiodiego requested changes
linter didn't like the trailing spaces

2019-10-02 12:36 UTC, rodrigok commented
What about adding a table like:

```markdown
| Release         | Cloud Service Support Deprecation | Cloud Service Support End of Life |
|-----------------|-----------------------------------|-----------------------------------|
| Rocket.Chat 0.x | Oktober 2019                      | January 2020                      |
| Rocket.Chat 1.x | January 2020                      | April 2020                        |
| Rocket.Chat 2.x | TBD                               | TBD                               |
```

A rule like:
- Deprecate support for 1.x 5 months after the release of 2.x
- Remove support 3 months after the deprecation

2019-10-03 16:50 UTC, rodrigok commented on getting-support/README.md
> +
```suggestion

3 months after a new major release, e.g. 2.x, the last major release, e.g. 1.x, will have the Services support deprecated and you may receive warnings about the deprecation.
5 months after the deprecation the support will be removed and you may receive erros and warnings about incompatibility.

| Release         | Cloud Service Support Deprecation | Cloud Service Support End of Life |
|-----------------|-----------------------------------|-----------------------------------|
| Rocket.Chat 0.x | August 2019                       | January 2020                      |
| Rocket.Chat 1.x | November 2019                     | April 2020                        |
| Rocket.Chat 2.x | TBD                               | TBD                               |
```

2019-10-05 20:21 UTC, rodrigok approved these changes

2019-10-05 20:21 UTC, merged