Docs for livechat visitor info endpoint
RocketChat/Rocket.Chat.Docs pull request #1481
Opened 2019-10-22 15:17 UTC by MarcosSpessatto

Waiting https://github.com/RocketChat/Rocket.Chat/pull/15639

2019-11-11 21:16 UTC, renatobecker-zz requested changes

2019-11-11 21:16 UTC, renatobecker commented on developer-guides/rest-api/livechat/visitor/README.md
> +| `/api/v1/livechat/visitors.info`           | `yes`          | `GET`       |
This is not aligned with the line above.

2019-11-11 21:16 UTC, renatobecker commented on developer-guides/rest-api/livechat/README.md
> +| `/api/v1/livechat/visitor.info` | `GET` | Retrieve a visitor info. | [info](visitor/index.html) |
```suggestion
| `/api/v1/livechat/visitors.info` | `GET` | Retrieve a visitor info. | [info](visitor/index.html) |
```

2019-12-23 14:48 UTC, MartinSchoeler approved these changes

2019-12-23 16:06 UTC, MartinSchoeler approved these changes

2019-12-23 16:06 UTC, merged