Refactoring Rasa kick starter document
RocketChat/Rocket.Chat.Docs pull request #1490
Opened 2019-10-28 20:29 UTC by sshniro

2019-10-31 19:11 UTC, bandantonio requested changes

2019-10-31 19:11 UTC, bandantonio commented on bots/running-a-rasa-bot/README.md
> +Rasa is developed with Python, but for the most part you dont need to know python to design the basic conversational flows in Rasa.
no comma needed before `but`

2019-10-31 19:11 UTC, bandantonio commented on bots/running-a-rasa-bot/README.md
>  # Running a Rasa Bot
Please check my PR here and refactor all the hedings according to the structure:
https://github.com/RocketChat/docs/pull/1445/files

2019-10-31 19:11 UTC, bandantonio commented on bots/running-a-rasa-bot/README.md
> +### Create Rocket.Chat Bot
All the steps related to creating a bot user are already described here: https://rocket.chat/docs/bots/create-and-run-a-bot/#steps

You can safely delete this section

2019-10-31 22:07 UTC, bandantonio commented
Working on updates to this PR.

Please, **DO NOT MERGE!**

2019-11-01 18:58 UTC, bandantonio commented
Consider closing this PR in favor of #1503

2019-11-02 15:41 UTC, sshniro commented
Closing the PR.

2019-11-02 15:41 UTC, closed without merging