Add guide to upgrade nodejs
RocketChat/Rocket.Chat.Docs pull request #1824
Opened 2020-11-14 17:45 UTC by truongtx8

#19537 Fix issue Rocketchat not starting when upgrading from 3.7.2 to 3.8.0

2020-11-14 17:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/docs?pullRequest=1824) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/docs?pullRequest=1824) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/docs?pullRequest=1824) it.</sub>

2020-11-28 11:32 UTC, Sing-Li requested changes
Can't assume the end user already has `n` installed.

2020-11-29 12:01 UTC, truongtx8 commented
> 
> 
> Can't assume the end user already has `n` installed.

The manual installation guide had `n` installed:
https://docs.rocket.chat/installation/manual-installation/debian

2021-03-04 15:00 UTC, Sing-Li approved these changes

2021-03-04 15:01 UTC, merged