Added clarification to setActiveStatus rest call
RocketChat/Rocket.Chat.Docs pull request #1866
Opened 2021-01-28 09:04 UTC by lennartgrunau

Added an explaination on the behaviour of `confirmRelinquish=true` when the user is the last remaining owner of a room.

2021-01-28 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/docs?pullRequest=1866) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/docs?pullRequest=1866) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/docs?pullRequest=1866) it.</sub>

2021-01-28 12:47 UTC, sampaiodiego requested changes

2021-01-28 12:58 UTC, lennartgrunau commented on api/rest-api/methods/users/setactivestatus.md
> +If `activeStatus=false` & `confirmRelinquish=true` and the user is the last remaining owner of a room, a new owner will be chosen randomly.
Yes, makes sense. Wasn't aware that is chooses the oldest member.

2021-02-08 17:30 UTC, sampaiodiego approved these changes

2021-02-08 17:30 UTC, merged