Add the missing documentation for the Rest API
RocketChat/Rocket.Chat.Docs pull request #192
Opened 2017-01-23 16:52 UTC by MartinSchoeler

Will add the following missing API methods to the documentation:
### Channel
  - [x] addOwner
  - [x] addModerator
  - [x] removeOwner
  - [x] removeModerator

### Group
  - [ ] addOwner
  - [ ] addModerator
  - [ ] removeOwner
  - [ ] removeModerator

### Im
  - [ ] setTopic
  - [ ] history
  - [ ] list
  - [ ] list.everyone
  - [ ] close
  - [ ] open

@graywolf336 if you see something wrong or if someone else already done any of the items above, please let me know

2017-01-23 16:58 UTC, graywolf336 submitted a review, later dismissed
Make sure you add them to the list of method calls on each `README.md` that is inside the folder of each type.

2017-01-27 18:15 UTC, MartinSchoeler commented
@graywolf336 did i miss anything or there is something wrong?

2017-01-31 11:16 UTC, graywolf336 requested changes

2017-01-31 11:16 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/messages.others.md
> +## Payload
When the http method is `GET` change this header to be `Query Parameters`.

2017-01-31 16:12 UTC, MartinSchoeler commented on 6. Developer Guides/REST API/Im/messages.others.md
> +## Payload
@graywolf336  Fixed! Also fixed the other errors like this one in some other files

2017-02-07 13:54 UTC, graywolf336 requested changes

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/README.md
> +# Im Methods
Capitalize the `IM` for all of the documentation for it.

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/README.md
> +From version 0.50.0 and on you can call the methods using `dm` instead of `im`.
Add a heading for this, maybe `## Notes`

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/list.everyone.md
> +# Im List.Eeveryone
`IM List Everyone`

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/list.everyone.md
> +Lists all of the direct messages in the server, this method supports the [Offset and Count Query Parameters](../Offset%20and%20Count%20Info.md).
Add a note about the permission this method requires.

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/messages.others.md
> +# Im Messages.others
`IM Messages Others`

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/messages.others.md
> +For this method work the `Enable Direct Message History Endpoint` setting must be true, and the user calling this method must have the `view-room-administration` permission.
Missing a **to** before `work`.

2017-02-07 13:54 UTC, graywolf336 commented on 6. Developer Guides/REST API/Im/open.md
> +# Channel Open
This is direct messages and not channels.

2017-02-13 20:29 UTC, graywolf336 approved these changes

2017-02-13 20:29 UTC, merged