Update and rename bitbucket-server-integration.md to bitbucket-cloud-…
RocketChat/Rocket.Chat.Docs pull request #1986
Opened 2021-05-29 03:42 UTC by maikondouglas

…integration.md

Request to update the Bitbucket Cloud installation/integration manual

2021-05-29 03:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/docs?pullRequest=1986) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/docs?pullRequest=1986) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/docs?pullRequest=1986) it.</sub>

2021-06-04 18:46 UTC, d-gubert commented
Hey @maikondouglas ! We'd be happy to have docs regarding our Bitbucket Cloud app, but the instructions to use it are different from the Bitbucket Server Integration app, which is a valid app btw, so we likely shouldn't remove those docs 🙂

2021-06-04 18:47 UTC, d-gubert requested changes
Hey @maikondouglas ! We'd be happy to have docs regarding our Bitbucket Cloud app, but the instructions to use it are different from the Bitbucket Server Integration app. Also, the Bitbucket Server Integration is a valid app, so we likely shouldn't remove those docs 🙂

2021-06-10 03:57 UTC, maikondouglas commented
I think it's interesting so you're creating this documentation for Bitbucket Cloud @d-gubert

2021-06-22 17:30 UTC, closed without merging