Update backup/restore documentation
RocketChat/Rocket.Chat.Docs pull request #211
Opened 2017-02-06 04:23 UTC by elespike

And a few extra styling edits

2017-02-20 19:03 UTC, geekgonecrazy submitted a review, later dismissed

2017-07-22 20:03 UTC, rafaelks commented
Is it still in progress @Sing-Li? There's a conflict on the PR.

2017-07-22 21:25 UTC, geekgonecrazy requested changes

2017-07-22 21:25 UTC, geekgonecrazy commented on 3. Installation/4. Manual Installation/Ubuntu/Snaps/README.md
> +
We need to add a warning here.  If a migration occured on the current version and they roll back it will fail to start.

2017-07-22 21:26 UTC, geekgonecrazy commented
All documentation there looks good.  We just need to fix conflicts

2017-09-22 19:08 UTC, engelgabriel commented
@geekgonecrazy can you resolve the conflicts and merge this?

2018-05-30 19:28 UTC, engelgabriel commented
Done via https://github.com/RocketChat/docs/commit/57398659e4b82ec1a91ec015dc3240db5992ee54

2018-05-30 19:28 UTC, closed without merging