Updated REST API README to include link to Ruby wrapper implementation
RocketChat/Rocket.Chat.Docs pull request #275
Opened 2017-04-25 09:19 UTC by abrom

Also fixed a few 404's in the Contributing/README

There is another Ruby rocket.chat library implementation here: https://github.com/int2xx9/ruby-rocketchat  although it supports API ~v0.1 so it may add confusion in linking to it??

2017-04-25 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=275) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=275) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Docs?pullRequest=275) it.</sub>

2017-04-25 17:17 UTC, graywolf336 commented
Thanks for the pull request!

Yeah I think I will agree with you, linking the Ruby wrapper might add some confusion since the api endpoints it references have been removed from any of the newer installations.

2017-04-25 17:19 UTC, graywolf336 requested changes

2017-04-25 17:19 UTC, graywolf336 commented on 6. Developer Guides/REST API/README.md
> +* [rocketchat-ruby](https://github.com/abrom/rocketchat-ruby)
Let's go ahead and remove this, due to the issue you mentioned.

2017-04-26 04:06 UTC, abrom commented on 6. Developer Guides/REST API/README.md
> +* [rocketchat-ruby](https://github.com/abrom/rocketchat-ruby)
@graywolf336 might have been a little misunderstanding here. The link in the PR is to a 'current' API implementation. The older one is https://github.com/int2xx9/ruby-rocketchat

2017-04-26 15:56 UTC, graywolf336 commented on 6. Developer Guides/REST API/README.md
> +* [rocketchat-ruby](https://github.com/abrom/rocketchat-ruby)
Ah okay, my bad.

2017-04-26 15:56 UTC, graywolf336 approved these changes

2017-04-26 15:56 UTC, merged