Add name parameter docs
RocketChat/Rocket.Chat.Docs pull request #280
Opened 2017-04-28 10:54 UTC by reist

Groups and Users info calls have included search by name for a number of versions already.

Channels would as well once [pull 6827](https://github.com/RocketChat/Rocket.Chat/pull/6827) is merged.

2017-05-01 21:15 UTC, graywolf336 requested changes

2017-05-01 21:15 UTC, graywolf336 commented on 6. Developer Guides/REST API/Channels/info.md
> +| `roomName` | `ByehQjC44FwMeiLbX` | Required (if no roomId) | The channel's name |
Can you change the example to be like a room name? This applies to all of these, thanks for the pull request!

2017-05-02 14:10 UTC, reist commented on 6. Developer Guides/REST API/Channels/info.md
> +| `roomName` | `ByehQjC44FwMeiLbX` | Required (if no roomId) | The channel's name |
Oops. Sure.

2017-06-04 11:24 UTC, reist commented
@graywolf336 Any chance for another review? I updated the commits a month ago.

2017-06-04 20:28 UTC, graywolf336 requested changes

2017-06-04 20:28 UTC, graywolf336 commented on 6. Developer Guides/REST API/Groups/info.md
> +| `roomName` | `Exclusive Chat` | Required (if no roomId) | The private group's name |
Spaces aren't allowed in the names of channels, so this wouldn't work..

2017-06-04 20:28 UTC, graywolf336 commented
I apologise for that, thanks for the reminder

2017-06-04 20:47 UTC, reist commented on 6. Developer Guides/REST API/Groups/info.md
> +| `roomName` | `Exclusive Chat` | Required (if no roomId) | The private group's name |
Ah, right. Fixed and pushed.

2017-06-05 17:31 UTC, graywolf336 approved these changes

2017-06-05 17:32 UTC, graywolf336 commented
Thanks for the pull request. I'll see about fixing the conflicts unless you want to.

2017-06-05 17:39 UTC, reist commented
@graywolf336 rebased and dropped the conflicting Users.info change. abrom added username there already.

2017-06-07 20:40 UTC, merged