Updated REST API users.list
RocketChat/Rocket.Chat.Docs pull request #281
Opened 2017-04-29 12:49 UTC by abrom

users.list documentation appeared to be a copy of the users.info?? Updated to match actual response. Also added 'query parameters' section with some examples of use

2017-04-29 22:25 UTC, graywolf336 commented
`v0.49` added the query, sort, and fields. Mind adding that to the history?

2017-04-30 04:48 UTC, abrom commented
Done!

What are your thoughts on some of the undocumented API endpoints? Namely:

* users.getAvatar
* users.register
* users.resetAvatar
* users.createToken

Is it a case of it just not having been written yet? Or intentionally undocumented

2017-04-30 04:58 UTC, graywolf336 commented
Yeah just a case of not being documented for whatever reason. Feel free to add them or I can add them, as I've been working on a decent sized documentation update for the APIs and integrations.

2017-04-30 05:01 UTC, abrom commented
No problems. I'll put something together

2017-06-12 19:59 UTC, graywolf336 requested changes

2017-06-12 19:59 UTC, graywolf336 commented on 6. Developer Guides/REST API/Users/list.md
> +## Query Parameters
Can you remove the offset, count, and sort ones as they're documented here: https://github.com/RocketChat/Rocket.Chat.Docs/blob/master/6.%20Developer%20Guides/REST%20API/Offset%20and%20Count%20Info.md then put a link to it somewhere in this document? Also, the fields and query ones need a dedicated document to further explain what features are enabled on them.. As the example provided will actually fail due to not being valid json format.

2017-07-09 10:42 UTC, abrom commented
Sorry for the delay @graywolf336. I've updated the docs as requested, and added details to the Offset and Count Info document about the `sort` query parameter

2017-07-22 20:02 UTC, rafaelks commented
@graywolf336 Can you review this PR again, please?

2017-08-10 19:53 UTC, graywolf336 approved these changes

2017-08-16 15:40 UTC, merged