Update AutoSSL.md
RocketChat/Rocket.Chat.Docs pull request #296
Opened 2017-05-24 15:25 UTC by drasbeck

Added description for which ports to open when behind a firewall/router.

2017-05-24 15:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=296) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=296) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Docs?pullRequest=296) it.</sub>

2017-05-24 17:59 UTC, geekgonecrazy requested changes
Lets hold off on merging this until we can verify for absolute sure that port 53 is required.  

I've done this several times and never needed inbound access to port 53

2017-05-24 17:59 UTC, geekgonecrazy commented on 3. Installation/4. Manual Installation/Ubuntu/Snaps/AutoSSL.md
> +- TCP/UDP dial-up: port **53**
From everything i've seen this shouldn't be required.

2017-05-24 18:03 UTC, drasbeck commented
I agree, this was drafted a bit prematurely. As long as I'm the only one expending this it should not go in the docs.

2017-05-25 15:55 UTC, geekgonecrazy commented
@drasbeck I think we figured it out in the [#ubuntu-snap](https://demo.rocket.chat/channel/ubuntu-snap) channel.  I think we can safely drop that and get the others merged.  Thanks :+1:

2017-06-05 11:07 UTC, frdmn commented
I guess we can close this :)

2017-06-07 20:48 UTC, geekgonecrazy commented
if we re-open and remove port 53 this might still be a useful note to add

2017-06-10 10:47 UTC, drasbeck commented
I agree, the first part contains valuable information but we should remove the part with port 53, since I needed to open this port due to another problem entirely, and thus it does not apply to everyone.

2017-06-14 11:18 UTC, drasbeck commented
Hi, I just removed the part with port 53.

2017-07-22 20:04 UTC, rafaelks commented
@geekgonecrazy Can you review this one again, please?

2017-07-22 21:20 UTC, geekgonecrazy approved these changes

2017-07-22 21:21 UTC, merged