Create README.md
RocketChat/Rocket.Chat.Docs pull request #313
Opened 2017-06-25 05:13 UTC by vishnupc

2017-06-25 05:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=313) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Docs?pullRequest=313) it.</sub>

2017-07-01 11:50 UTC, vishnupc reviewed
Added necessary details.

2017-07-01 19:57 UTC, geekgonecrazy requested changes

2017-07-01 19:57 UTC, geekgonecrazy commented on 3. Installation/2. PaaS Deployments/ReadySpace/README.md
> +Deploying Rocket.Chat on ReadySpce Cloud
Looks like missing an `a` in Readyspace :smile:

2017-07-22 20:06 UTC, rafaelks commented
@geekgonecrazy Can you review it again, please?

2017-07-22 21:19 UTC, geekgonecrazy approved these changes

2017-07-22 21:19 UTC, merged

2017-07-22 21:20 UTC, geekgonecrazy commented
@vishnupc thanks for the contribution :+1:

2017-07-23 17:41 UTC, vishnupc commented
Thank You @geekgonecrazy for merging my request.