Nixstats incoming webhook script
RocketChat/Rocket.Chat.Docs pull request #321
Opened 2017-07-05 13:48 UTC by vfuse

Receive notifications from nixstats.com in rocket.chat

2017-07-05 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=321) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=321) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Docs?pullRequest=321) it.</sub>

2017-07-06 15:58 UTC, geekgonecrazy submitted a review, later dismissed

2017-07-06 15:58 UTC, geekgonecrazy commented on 5. Administrator Guides/Integrations/nixstats.md
> +Paste this in javascript in the "Script" textarea on Rocket.Chat webhook settings
> Paste this in javascript in the "Script"

Should be something like:
> Paste this in the "Script" 
or
> Paste this javascript in the "Script"

2017-07-06 15:58 UTC, geekgonecrazy commented
@sampaiodiego will the backticks in the script be a problem for the docs renderer?

2017-07-22 20:39 UTC, sampaiodiego submitted a review, later dismissed

2017-07-22 20:39 UTC, sampaiodiego commented on 5. Administrator Guides/Integrations/nixstats.md
> +```/* exported Script */
please start the code on a new line

2017-07-22 20:39 UTC, sampaiodiego commented on 5. Administrator Guides/Integrations/nixstats.md
> +```/* exported Script */
please start the code on a new line

2017-07-22 20:39 UTC, sampaiodiego commented on 5. Administrator Guides/Integrations/nixstats.md
> +<img src="https://github.com/NIXStats/Nixstats-integrations/blob/master/rocketchat/serverlist.png" data-canonical-src="graphs.png" width="400" />
this image does not render

2017-07-22 20:39 UTC, sampaiodiego commented on 5. Administrator Guides/Integrations/nixstats.md
> +<img src="https://github.com/NIXStats/Nixstats-integrations/blob/master/rocketchat/graphs.png" data-canonical-src="graphs.png" width="400" />
this image does not render

2017-08-02 14:52 UTC, SeanPackham commented on 5. Administrator Guides/Integrations/nixstats.md
> +```/* exported Script */
@vfuse could you address @sampaiodiego and then we can get this merged!

2017-08-04 17:35 UTC, geekgonecrazy commented on 5. Administrator Guides/Integrations/nixstats.md
> +Paste this in javascript in the "Script" textarea on Rocket.Chat webhook settings
@vfuse Also this is a small one, but greatly helps readability.

@SeanPackham  :top:

2017-08-17 14:25 UTC, vfuse reviewed
Starting code on newline

2017-08-17 19:13 UTC, geekgonecrazy requested changes

2017-08-17 19:13 UTC, geekgonecrazy commented on 5. Administrator Guides/Integrations/nixstats.md
> +Paste this in javascript in the "Script" textarea on Rocket.Chat webhook settings
Please adjust the wording here to something like:
> Paste this javascript in the "Script" textarea on Rocket.Chat webhook settings

2017-08-18 17:04 UTC, geekgonecrazy approved these changes

2017-08-18 17:05 UTC, geekgonecrazy commented
Thanks for your contribution @vfuse sorry for so many little changes.

2017-08-18 17:05 UTC, merged