improved subfolder-documentation
RocketChat/Rocket.Chat.Docs pull request #323
Opened 2017-07-08 19:08 UTC by Iridias

After spending half a day in frustration before finally getting rocket.chat running in a subfolder, I felt that I should share my findings with others.
Thus I improved the - to that point not very helpful - documentation about subfolder-support.

2017-07-08 19:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=323) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Docs?pullRequest=323) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Docs?pullRequest=323) it.</sub>

2017-07-10 16:31 UTC, geekgonecrazy requested changes

2017-07-10 16:31 UTC, geekgonecrazy commented on 3. Installation/4. Manual Installation/Running in a sub folder.md
> +- Using the RewriteBase Directive won't work - I tried it
Maybe remove the "I tried it" bit here.

2017-07-10 16:31 UTC, geekgonecrazy commented on 3. Installation/4. Manual Installation/Running in a sub folder.md
> +If you followed the manual installation guide, you may already have configured (and persisted) this evironment variable - in this case you can ignore this advice.
`evironment variable` -> `environment variable`

2017-07-10 16:31 UTC, geekgonecrazy commented
@Iridias thanks for contributing these improvements.  Hopefully this will help others.  Left a couple of small notes

2017-07-17 16:56 UTC, geekgonecrazy requested changes

2017-07-17 16:56 UTC, geekgonecrazy commented on 3. Installation/4. Manual Installation/Running in a sub folder.md
> +If you followed the manual installation guide, you may already have configured (and persisted) this evironment variable - in this case you can ignore this advice.
You got the previous instance of this but can you change:

`evironment variable` -> `environment variable`

2017-07-18 05:42 UTC, Iridias commented on 3. Installation/4. Manual Installation/Running in a sub folder.md
> +If you followed the manual installation guide, you may already have configured (and persisted) this evironment variable - in this case you can ignore this advice.
Oops, my bad. Commit incoming.

2017-07-22 20:06 UTC, rafaelks commented
@geekgonecrazy Can you review it again, please?

2017-07-22 21:17 UTC, geekgonecrazy approved these changes

2017-07-22 21:18 UTC, geekgonecrazy commented
@Iridias thanks!  Last thing is to click through and review the CLA and we'll be good to merge :+1:

2017-08-02 10:43 UTC, docsncode approved these changes

2017-08-02 10:43 UTC, merged