Added D2Cio to paas deployments
RocketChat/Rocket.Chat.Docs pull request #483
Opened 2017-12-28 07:34 UTC by mastappl

D2C is a private virtual PaaS. 
Added description to easy deploying Rocket.Chat to linked cloud providers or own server with a single click.

2018-01-26 12:13 UTC, MartinSchoeler requested changes

2018-01-26 12:13 UTC, MartinSchoeler commented on installation/paas-deployments/d2cio/README.md
> +# Deploying Rocket.Chat on D2C.io
Please add this file to the [Table of Contents](https://github.com/RocketChat/docs/blob/master/_data/toc.yml)

2018-01-30 13:09 UTC, mastappl commented
Hi,
Could you please repeat the check?

2018-02-15 13:25 UTC, MartinSchoeler approved these changes

2018-02-15 13:25 UTC, merged

2018-02-15 13:26 UTC, MartinSchoeler commented
Thanks for the contribution!