Add docs on '?layout=embedded'
RocketChat/Rocket.Chat.Docs pull request #681
Opened 2018-04-10 14:47 UTC by MartinSchoeler

closes #89

2018-04-11 12:10 UTC, sampaiodiego requested changes

2018-04-11 12:10 UTC, sampaiodiego commented on _data/toc.yml
> +    - Layout Embedded
Should this be changed to `Embedded Layout` as of [page's title](https://github.com/RocketChat/docs/pull/681/files#diff-21a9468c9abb601c7f3650003dd3ae19R1)

2018-04-11 12:10 UTC, sampaiodiego commented on contributing/documentation/documentation-map/README.md
> +    - Layout Embedded
Should this be changed to `Embedded Layout` as of [page's title](https://github.com/RocketChat/docs/pull/681/files#diff-21a9468c9abb601c7f3650003dd3ae19R1)

2018-04-11 12:10 UTC, sampaiodiego commented on developer-guides/layout-embedded/README.md
> +If you are embedding Rocket.Chat in your site, you can change Rocket.Chat's layout by adding `?layout=embedded` after your server url.
please change all `url` to capital `URL` along whole page.

2018-04-11 13:29 UTC, MartinSchoeler commented
@sampaiodiego Fixed the reviews

2018-04-12 01:56 UTC, sampaiodiego approved these changes

2018-04-13 13:44 UTC, merged