Update Documentation: REST API (users.setAvatar)
RocketChat/Rocket.Chat.Docs pull request #954
Opened 2018-10-16 18:55 UTC by TopHattedCat

Update the setAvatar docs to add the image argument to the arguments list, and change the wording of the avatarUrl argument.

2018-10-16 18:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/docs?pullRequest=954) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/docs?pullRequest=954) before we can accept your contribution.<br/><hr/>**Sam Simpson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/docs?pullRequest=954) it.</sub>

2018-10-16 20:21 UTC, MarcosSpessatto requested changes
I think you should explain that the `image` parameter is only sent by `form-data`, because the way you put it, it looks like it might be sent by the `POST` request payload. What do you think of putting a new section describing which fields should be sent if the user wants to upload the image(send by `form-data`)?

2018-10-18 22:13 UTC, TopHattedCat commented
I've split the page into two, one for when you want to upload a file and one for when you're specifying a URL and clarified that the image needs to be sent as form data.

2018-10-19 19:48 UTC, MarcosSpessatto approved these changes

2018-10-19 19:48 UTC, MarcosSpessatto commented
@TopHattedCat  thanks! :+1:

2018-10-25 20:10 UTC, merged