[New Documentation] Added E2E methods
RocketChat/Rocket.Chat.Docs pull request #985
Opened 2018-11-13 17:07 UTC by Hudell

2018-11-13 17:55 UTC, rafaelks commented
@Hudell Can you please add the minimum version required to use this APIs?

2018-11-13 18:08 UTC, Hudell commented
I added a changelog at the end of each file with the version the methods were included on.

2018-11-14 10:22 UTC, rafaelks requested changes
@Hudell Thank you! The only thing now is that you only added the documentation for the real-time methods... can you also add it to the REST APIs please?

2020-06-11 05:05 UTC, engelgabriel approved these changes

2020-06-11 05:05 UTC, merged